### PR TITLE
automatic installation of driver manager chrome

### PR DESCRIPTION
**Pull request by Axel3026**
Well I hope you like it, I don't know if it works or if you see something you don't like let me know, I just want to speed things up

### CODE REVIEW

**Comment by Axel3026** [comment]
I don't understand what is happening but it is throwing me errors like these


```
Traceback (most recent call last):
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Descargas\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1482, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "E:\Descargas\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 99, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Descargas\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1613, in <module>
    main()
  File "E:\Descargas\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1599, in main
    farmer()
  File "E:\Descargas\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1559, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Comment by Axel3026** [comment]
https://pypi.org/project/webdriver-manager/

**Comment by farshadz1997** [comment]
It seems like that it didn't work properly and webdriver file could not found by Selenium. This would be useful, please complete this and fix bugs then I'll merge it.

**Comment by Axel3026** [comment]
> It seems like that it didn't work properly and webdriver file could not found by Selenium. This would be useful, please complete this and fix bugs then I'll merge it.

muchas gracias por responder, ojala fuera facil arreglar esto, si supiera programar

**Comment by Axel3026** [comment]
Now yes, the --account argument doesn't let me or appear in the list, it doesn't give me an error or anything, I don't understand

**Pull request closed without merging**
