### PR TITLE
--calculator, --superfast, and --redeem (CREDITS:  dmarts05)

### PR DESCRIPTION
**Pull request by Prabh-Saini**
NOTE: `--autoredeem` is fully developed by @dmarts05, all I did was add merge the feature into my branch, which consisted of clicking ctrl+c and ctrl+v lol. 

This pull brings `--calculator`, `--superfast`, and `--autoredeem`. --superfast is at least 50% faster than --fast, and in some cases up to 1200% faster than normal speed. --calculator is a tkinter based calculator based on my github repository https://github.com/Prabh-Saini/msrewardsestimator, activated by using `--calculator` which prevents the script from running and opens the window below. I've added the appropriate information in readme.md and added calculator.bat in setup.md. The UI uses tkinter therefore it should run well on macOS, Windows, and Linux. on all CPU architectures including raspberry pi (armv8). Meaning there is no compatibility issues. `--autoredeem` is used to automatically redeem a reward in microsoft rewards, the appropriate MD file has been added alongside it. 

image

### CODE REVIEW

**Comment by Prabh-Saini** [comment]
I've added the appropriate information in readme.md and added calculator.bat in setup.md. note: before pulling this branch, make sure to pull #152 first as this is based upon the code of #152. 

The UI uses tkinter therefore it should run well on macOS, Windows, and Linux. on all CPU architectures including raspberry pi (armv8) I believe.

**Comment by Prabh-Saini** [comment]
Fixed all deepsource issues, read above for other stuff.

**Comment by Prabh-Saini** [comment]
Needs to be tested before merging the pull request.

**Comment by farshadz1997** [comment]
Have you tested auto redeem personally?

**Comment by Prabh-Saini** [comment]
no i haven't tested auto redeem personally its only an adaptation of #154, i can't redeem anything at the moment.

**Comment by Prabh-Saini** [comment]
Upon further testing, it successfully reads, and writes goals to the MS web interface however in my testing it did not automatically redeem or even alert that the option to redeem was available. The redeem function needs to be worked on a bit more before I say it should be merged.

**Comment by leatherhead645** [comment]
Hi, so I looked at your MSRewardEstimator and I am  quite confused in where you get your numbers from. 


`microsoft = 4750  # price of microsoft/xbox gift cards`
`non_microsoft = 6750  # price of 3rd party gift cards`

I was going to build it into MS Reward Bot GUI V2, but I don't understand calculations.

**Comment by dmarts05** [comment]
> Upon further testing, it successfully reads, and writes goals to the MS web interface however in my testing it did not automatically redeem or even alert that the option to redeem was available. The redeem function needs to be worked on a bit more before I say it should be merged.

As soon as I get one account to the minimum amount of points to redeem a card, I'll try an fix it. I had to blindly put the code together so it makes sense that it doesn't work xD

**Comment by Prabh-Saini** [comment]
> Hi, so I looked at your MSRewardEstimator and I am quite confused in where you get your numbers from.
> 
> `microsoft = 4750 # price of microsoft/xbox gift cards` `non_microsoft = 6750 # price of 3rd party gift cards`
> 
> I was going to build it into MS Reward Bot GUI V2, but I don't understand the calculations.

Hey mate, those values are the price of purchasing a gift card in MS rewards. (at least in Australia), for example a $5 amazon gift card is 6750 points and a $5 microsoft/xbox giftcard is 4750 points.

**Comment by Prabh-Saini** [comment]
@dmarts05 Turns out I forgot the most vital part of the code, the part where it calls redeemGoal() haha. Anyway I've tested it with a $1 UNICEF donation and it works (mostly) perfectly. Although, it did give me some errors which seem pretty simple to resolve. terminal logs (`py main.py --redeem --superfast --error --discord [WEBHOOK]`)
```
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully!
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="productCheckoutChallenge"]/form/div[1]"}
  (Session info: chrome=111.0.5563.65)
Stacktrace:
Backtrace:
        (No symbol) [0x00A837D3]
        (No symbol) [0x00A18B81]
        (No symbol) [0x0091B36D]
        (No symbol) [0x0094D382]
        (No symbol) [0x0094D4BB]
        (No symbol) [0x00983302]
        (No symbol) [0x0096B464]
        (No symbol) [0x00981215]
        (No symbol) [0x0096B216]
        (No symbol) [0x00940D97]
        (No symbol) [0x0094253D]
        GetHandleVerifier [0x00CFABF2+2510930]
        GetHandleVerifier [0x00D28EC1+2700065]
        GetHandleVerifier [0x00D2C86C+2714828]
        GetHandleVerifier [0x00B33480+645344]
        (No symbol) [0x00A20FD2]
        (No symbol) [0x00A26C68]
        (No symbol) [0x00A26D4B]
        (No symbol) [0x00A30D6B]
        BaseThreadInitThunk [0x76AD7D69+25]
        RtlInitializeExceptionChain [0x779BBB9B+107]
        RtlClearBits [0x779BBB1F+191]

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="productCheckoutError"]/div/div[1]"}
  (Session info: chrome=111.0.5563.65)
Stacktrace:
Backtrace:
        (No symbol) [0x00A837D3]
        (No symbol) [0x00A18B81]
        (No symbol) [0x0091B36D]
        (No symbol) [0x0094D382]
        (No symbol) [0x0094D4BB]
        (No symbol) [0x00983302]
        (No symbol) [0x0096B464]
        (No symbol) [0x00981215]
        (No symbol) [0x0096B216]
        (No symbol) [0x00940D97]
        (No symbol) [0x0094253D]
        GetHandleVerifier [0x00CFABF2+2510930]
        GetHandleVerifier [0x00D28EC1+2700065]
        GetHandleVerifier [0x00D2C86C+2714828]
        GetHandleVerifier [0x00B33480+645344]
        (No symbol) [0x00A20FD2]
        (No symbol) [0x00A26C68]
        (No symbol) [0x00A26D4B]
        (No symbol) [0x00A30D6B]
        BaseThreadInitThunk [0x76AD7D69+25]
        RtlInitializeExceptionChain [0x779BBB9B+107]
        RtlClearBits [0x779BBB1F+191]

[REDEEM] EMAIL@hotmail.com card redeemed!
[POINTS] You have earned 0 points today !
[POINTS] You are now at 1439 points !

[LOGS] Report sent to Discord.

Farmer finished in: 00:02:59
Farmer finished on 17-03-2023 22:40:28
Press enter to close the program...
```

**Comment by Prabh-Saini** [comment]
@farshadz1997 The branch is finally ready to be merged in to the main. All the features have been tested and none of them return any errors, and work completely when run in an appropriate environment. All deepsource issues have been fixed.

**Comment by dmarts05** [comment]
> @dmarts05 Turns out I forgot the most vital part of the code, the part where it calls redeemGoal() haha. Anyway I've tested it with a $1 UNICEF donation and it works (mostly) perfectly. Although, it did give me some errors which seem pretty simple to resolve. terminal logs (`py main.py --redeem --superfast --error --discord [WEBHOOK]`)
> 
> ```
> [LOGIN] Logging-in...
> [LOGIN] Writing email...
> [LOGIN] Writing password...
> [LOGIN] Passing security checks...
> [LOGIN] Logged-in !
> [LOGIN] Logging into Microsoft Rewards...
> [LOGIN] Ensuring login on Bing...
> [LOGIN] Logged-in successfully!
> Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="productCheckoutChallenge"]/form/div[1]"}
>   (Session info: chrome=111.0.5563.65)
> Stacktrace:
> Backtrace:
>         (No symbol) [0x00A837D3]
>         (No symbol) [0x00A18B81]
>         (No symbol) [0x0091B36D]
>         (No symbol) [0x0094D382]
>         (No symbol) [0x0094D4BB]
>         (No symbol) [0x00983302]
>         (No symbol) [0x0096B464]
>         (No symbol) [0x00981215]
>         (No symbol) [0x0096B216]
>         (No symbol) [0x00940D97]
>         (No symbol) [0x0094253D]
>         GetHandleVerifier [0x00CFABF2+2510930]
>         GetHandleVerifier [0x00D28EC1+2700065]
>         GetHandleVerifier [0x00D2C86C+2714828]
>         GetHandleVerifier [0x00B33480+645344]
>         (No symbol) [0x00A20FD2]
>         (No symbol) [0x00A26C68]
>         (No symbol) [0x00A26D4B]
>         (No symbol) [0x00A30D6B]
>         BaseThreadInitThunk [0x76AD7D69+25]
>         RtlInitializeExceptionChain [0x779BBB9B+107]
>         RtlClearBits [0x779BBB1F+191]
> 
> Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="productCheckoutError"]/div/div[1]"}
>   (Session info: chrome=111.0.5563.65)
> Stacktrace:
> Backtrace:
>         (No symbol) [0x00A837D3]
>         (No symbol) [0x00A18B81]
>         (No symbol) [0x0091B36D]
>         (No symbol) [0x0094D382]
>         (No symbol) [0x0094D4BB]
>         (No symbol) [0x00983302]
>         (No symbol) [0x0096B464]
>         (No symbol) [0x00981215]
>         (No symbol) [0x0096B216]
>         (No symbol) [0x00940D97]
>         (No symbol) [0x0094253D]
>         GetHandleVerifier [0x00CFABF2+2510930]
>         GetHandleVerifier [0x00D28EC1+2700065]
>         GetHandleVerifier [0x00D2C86C+2714828]
>         GetHandleVerifier [0x00B33480+645344]
>         (No symbol) [0x00A20FD2]
>         (No symbol) [0x00A26C68]
>         (No symbol) [0x00A26D4B]
>         (No symbol) [0x00A30D6B]
>         BaseThreadInitThunk [0x76AD7D69+25]
>         RtlInitializeExceptionChain [0x779BBB9B+107]
>         RtlClearBits [0x779BBB1F+191]
> 
> [REDEEM] EMAIL@hotmail.com card redeemed!
> [POINTS] You have earned 0 points today !
> [POINTS] You are now at 1439 points !
> 
> [LOGS] Report sent to Discord.
> 
> Farmer finished in: 00:02:59
> Farmer finished on 17-03-2023 22:40:28
> Press enter to close the program...
> ```

Nice! I forgot to remove those prints. I left them there for debugging purposes. Have you also included the custom message I added for auto-redeem? If so, is it working correctly?

**Comment by Prabh-Saini** [comment]
If by custom message you mean this: (discord webhook)
image
then yes

**Comment by dmarts05** [comment]
> If by custom message you mean this: (discord webhook) image then yes

Awesome! Then it should be good to go.

**Comment by Prabh-Saini** [comment]
Added like 60 lines of just documentation
image
This alone fixes fixes 62 of the 344 issues (18%) in master branch according to deepsource, reducing the number of issues to 282. 
image

**Comment by farshadz1997** [comment]
@Prabh-Saini Nice job man, I want to ask you to add a field for average daily earn to your calculator, I saw have set it to 240 which is average daily earn in Australia, for US accounts is about 400 and Europe is different I guess, if you add this then it can calculate with less margin error.

**Comment by Prabh-Saini** [comment]
makes me salty i only make 240 haha, but yeah i will add it and also disable the gui when running on headless. i wont have access to my laptop for a day or two and also have a test on Monday but ill figure it out soon lol.

**Comment by Prabh-Saini** [comment]
All checks passed, ready to be merged @farshadz1997.

**Comment by raycekar** [comment]
Can we add a check for tkinter installed or not before importing? I did not have it initially installed and came around to find it was crashing to import it and for those that may or may not use that functionality.

**Comment by Prabh-Saini** [comment]
> Can we add a check for tkinter installed or not before importing? I did not have it initially installed and came around to find it was crashing to import it and for those that may or may not use that functionality.

Hey Raycekar,
Although this is a good idea. The issue is that I'm working on a auto update feature which would automatically update pip modules, and therefore this seems really redundant. Although the feature will take maybe a few weeks because I've just been busy and also have like 3 assignments due at the moment.

**Comment by farshadz1997** [comment]
> Can we add a check for tkinter installed or not before importing? I did not have it initially installed and came around to find it was crashing to import it and for those that may or may not use that functionality.

Hi
Tkinter module installs with Python and you don't need to install it separately. that's weird that you didn't have it.

**Comment by dmarts05** [comment]
> > Can we add a check for tkinter installed or not before importing? I did not have it initially installed and came around to find it was crashing to import it and for those that may or may not use that functionality.
> 
> Hi Tkinter module installs with Python and you don't need to install it separately. that's weird that you didn't have it.

That's not the case for my Linux machine.

**Comment by Prabh-Saini** [comment]
tbh i didnt even know some python versions on linux came without tkinter. right now my goal is to fix msn shopping because its destroying the amount of points i could make.

**Comment by dmarts05** [comment]
> tbh i didnt even know some python versions on linux came without tkinter. right now my goal is to fix msn shopping because its destroying the amount of points i could make.

That's awesome. If you need any help hit me up. I am trying to improve the overall performance of the script and adding some anti ban measures. I'll probably make a pull request when I find some free time next week.

**Pull request merged**
