### PR TITLE
Check if msn game is finished

### PR DESCRIPTION
**Pull request by tommaso-ascani**
Hi everyone, i have recoded this func and i hope it's better than the old PR.
This is the first version so i ask @farshadz1997 and @Prabh-Saini (or everyone else) to control it and in case tell me what can i improve or change.
I tested and works but surely there is something i can do better, so i wait for some advice! 😄

### CODE REVIEW

**Comment by Morena36** [comment]
```
javascript:	
var msnShoppingGamePane = document.querySelector("shopping-page-base")
?.shadowRoot.querySelector("shopping-homepage")
?.shadowRoot.querySelector("msft-feed-layout")
?.shadowRoot.querySelector("msn-shopping-game-pane");

                                if (msnShoppingGamePane != null){
                                 msnShoppingGamePane.style.setProperty("grid-area", "slot1");
    msnShoppingGamePane.setAttribute('gamestate', 'active'); 
    msnShoppingGamePane.cardsPerGame = 1;
    msnShoppingGamePane.resetGame();
}   
else alert("Unable to locate the shopping game!");
```

Hello, if you like, you can add this code "javascript:" so that it only loads a single card, since you might like it, the truth is that this MSN works excellent, but it has an error since I only farmed 90 points and I was missing 10 It would be nice if you could implement the game reset so that when you reach 10 you have one more try just in case to ensure that the 100 points were completed correctly

**Comment by Morena36** [comment]
```
    def moveCards() -> None:
        """move up the cards"""
        browser.execute_script("""var msnShoppingGamePane = document.querySelector("shopping-page-base")
                                            ?.shadowRoot.querySelector("shopping-homepage")
                                            ?.shadowRoot.querySelector("msft-feed-layout")
                                            ?.shadowRoot.querySelector("msn-shopping-game-pane");
                                        if (msnShoppingGamePane != null) {
                                            msnShoppingGamePane.style.setProperty("grid-area", "slot1");
                                            msnShoppingGamePane.setAttribute('gamestate', 'active'); 
                                            msnShoppingGamePane.cardsPerGame = 1;
                                            msnShoppingGamePane.resetGame();
                                        }""")
        time.sleep(calculateSleep(2))

```

**Comment by Morena36** [comment]
It was a bad idea, it opens many pages for me hahaha

**Comment by tommaso-ascani** [comment]
@Morena36 I will check if it do not farm all the 100 points but i preferred don't reset the game beacuse also the game state get reset and it's not comfy for the code flow but thanks i will check it.
There aren't many opened pages, only one tab get opened to control if the game is finished and immediately after the check it is closed

**Comment by Morena36** [comment]
When I get home I'll see if I can record and I'll show you how it worked for me, you're right about the reset, since that seemed like a good idea to me.

**Comment by Morena36** [comment]
"I discovered something: when I'm running the program with this code ``'profile.managed_default_content_settings.images': 2,``  it doesn't work because the whole page doesn't load. Maybe it would be nice if it could be deactivated when accessing MSN."

**Pull request closed without merging**
