### PR TITLE
fix: Add extra delays to punch cards and this or that.

### PR DESCRIPTION
**Pull request by dmarts05**
Superfast is unrealiable even with good hardware and a really good Internet connection. This is why I had to increase some delays so it can work properly on the majority of systems.

### CODE REVIEW

**Comment by Prabh-Saini** [comment]
This update does sort of hurt users not running --fast or --superfast but regardless, it looks good and should definitely get pushed in. @farshadz1997

**Comment by dmarts05** [comment]
> This update does sort of hurt users not running --fast or --superfast but regardless, it looks good and should definitely get pushed in. @farshadz1997

One solution would be to hard code these changes, but I don't think that there's a lot of people using the bot without fast mode active.

**Comment by farshadz1997** [comment]
> > This update does sort of hurt users not running --fast or --superfast but regardless, it looks good and should definitely get pushed in. @farshadz1997
> 
> One solution would be to hard code these changes, but I don't think that there's a lot of people using the bot without fast mode active.

I think using waitUntilVivible and waitUntilClickable functions with high timeout before the slee would be better idea, it acts fasts for those have a good internet and it acts normal for others

**Comment by dmarts05** [comment]
> > > This update does sort of hurt users not running --fast or --superfast but regardless, it looks good and should definitely get pushed in. @farshadz1997
> > 
> > 
> > One solution would be to hard code these changes, but I don't think that there's a lot of people using the bot without fast mode active.
> 
> I think using waitUntilVivible and waitUntilClickable functions with high timeout before the slee would be better idea, it acts fasts for those have a good internet and it acts normal for others

That's definitely a better solution. I'll try to implement it as soon as I have some free time.

**Pull request closed without merging**
