### PR TITLE
Add -no-update argument

### PR DESCRIPTION
**Pull request by V1NAY007**
Generally helpful if someone has made modifications in script for their system and it updates and need to do those again.

For ex - my self-hosted windows workflow doesnt support ANSI characters so i made modifications locally to encode to utf-8 and each update it would reset and fail.

### CODE REVIEW

**Comment by Prabh-Saini** [comment]
i'm not sure if you understand what that function does. it does NOT update the script, it only warns the user of an outdated script. In order to update the script you have to run `py update.py --update -y`

**Comment by V1NAY007** [comment]
@Prabh-Saini Ohh I'm sorry my bad. Im very new to python and coding, so I didn't knew that, I'll just delete this pull request then

**Comment by Prabh-Saini** [comment]
instead of closing it i think if you rename the flag to --dont-check-for-updates and push it in i think its a good pull request. it was actually on this of things need doing, but you've already developed it!

**Comment by Prabh-Saini** [comment]
Superseded by #210, I greatly appreciate your contribution and I have put your work in to the new commit. Thank you for spending the time to create this code, what I have done is simply copy and pasted, but you have done the real work. I've given appropriate credits.

**Pull request closed without merging**
