### PR TITLE
user agent modified

### PR DESCRIPTION
**Pull request by FRKFFR**
because the mobile user agent on the web page says you have to install bing mobile

### CODE REVIEW

**Comment by farshadz1997** [comment]
You are using chrome 97 which is too old for Chrome web driver, and it can expose that you are using bot

**Comment by FRKFFR** [comment]
now is good ?

**Comment by farshadz1997** [comment]
I think I got your point; you want to use Microsoft Edge user-agent like this, if is that so use this, there is still conflict in yours.
```Mozilla/5.0 (Linux; Android 12; SM-N9750) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36 EdgA/106.0.1370.47```

**Comment by FRKFFR** [comment]
ok

**Comment by DerMuffin** [comment]
Does this fix the issue with not working mobile searches because of this bing pop-up blocking all elemtents?

@FRKFFR @farshadz1997

**Comment by farshadz1997** [comment]
@DerMuffin What element? I already bypass every element that mentioned in issues. this user-agent might help with that.

**Comment by DerMuffin** [comment]
> @DerMuffin What element? I already bypass every element that mentioned in issues. this user-agent might help with that.

Works perfectly when applying fix from @FRKFFR

**Pull request closed without merging**
