### PR TITLE
Add --account-file flag

### PR DESCRIPTION
**Pull request by Akianonymus**
It works for relative paths too.

Easy to use multiple accounts without renaming to accounts.json everytime

### CODE REVIEW

**Comment by Akianonymus** [comment]
I have fixed the conflicts.

**Comment by Prabh-Saini** [comment]
Code looks good, if you know how to, it would be nice if you could make it so you can have multiple accounts.json

**Comment by Akianonymus** [comment]
I have pushed the code

**Comment by richard892** [comment]
> I have pushed the code

i am non coder, how can i use it?
I want to run accounts in parallel.

**Review by Chappie18 — COMMENTED** [review]
Can you mention the argument example too

**Comment by richard892** [comment]
> Thank you

how to use, please explain

**Comment by V1NAY007** [comment]
> > I have pushed the code
> 
> i am non coder, how can i use it? I want to grind accounts in parallel.

No support for non coders

**Comment by Akianonymus** [comment]
@farshadz1997 Any chance of merging this ?

**Comment by Akianonymus** [comment]
> > I have pushed the code
> 
> i am non coder, how can i use it? I want to grind accounts in parallel.

This pr is not related to that.

**Comment by farshadz1997** [comment]
> @farshadz1997 Any chance of merging this?

I like your idea but I don't see any difference between farming all accounts from one file or farming all from multiple files. also, it's not good to loop over them, I want to refactor the code, and this is quite the opposite.

**Comment by Akianonymus** [comment]
It's just the matter of convenience. Suppose i have multiple json files, i have oragnized them into different different json files, now i have to rename it to accounts.json ( or copy that json to accounts.json ) every time i want to use the file. With this flag i can just specify the different account file name, what's the harm here ? Also, i get seperate log files which is again useful when i just want to reset those accounts.

Also, about looping, why it's not good to loop over them ? Anyway we can drop the multiple accounts files support, so there will be no looping

Can you specify what you want to refactor ?

**Comment by farshadz1997** [comment]
> It's just the matter of convenience. Suppose i have multiple json files, i have oragnized them into different different json files, now i have to rename it to accounts.json ( or copy that json to accounts.json ) every time i want to use the file. With this flag i can just specify the different account file name, what's the harm here ? Also, i get seperate log files which is again useful when i just want to reset those accounts.
> 
> Also, about looping, why it's not good to loop over them ? Anyway we can drop the multiple accounts files support, so there will be no looping
> 
> Can you specify what you want to refactor ?

I mean that you choose the account file name you want not the list of files, and you override the ```accounts.json``` with this command for example: ```--accounts-file new_accounts.json```

**Comment by Akianonymus** [comment]
Yeah, that's how it is working. What do you mean by override the accounts.json ? That it will use the new file ? Yes that's how it is working

**Comment by farshadz1997** [comment]
> Yeah, that's how it is working. What do you mean by override the accounts.json ? That it will use the new file ? Yes that's how it is working

the bot looks for ```accounts.json``` as the default file, I mean you could easily change this if your accounts file has another name. but in this case ```--account-file``` accepts only 1 value and check if that file exists in bot directory then it will open that instead of ```accounts.json```.
the main problem of looping over files in the main function is that if somebody uses ```--start-at <TIME>``` then the bot waits for that time when the first file is finished, but the solution I'm talking about is more straight and simpler.

**Comment by Insomniac5** [comment]
> > @farshadz1997 Any chance of merging this?
> 
> I like your idea but I don't see any difference between farming all accounts from one file or farming all from multiple files. also, it's not good to loop over them, I want to refactor the code, and this is quite the opposite.
> 
> instead, you can change it to an option for the user to choose the account file name.

Honestly though I find the json selection quite useful, I normally run multiple scripts in parallel and for that I've had multiple jsons set already. Originally I had to edit the main program and make like 30 copies just each using a different json, with this option it just saves that entire time.

My issue can also be solved my the method you mentioned which is selecting the account to farm instead of the json, however it's easier with different logs for all accounts mahes it so much more easier to look for things.

**Comment by farshadz1997** [comment]
@Insomniac5, it will also create a log with the name same as the selected accounts file.

**Comment by V1NAY007** [comment]
I think should instead add --accounts argument which takes email and pass, for ex - "--accounts susemail@gmail.com:suspassword", and also a --privacy argument,which hides --account argument from displaying. from what i remember, there was already a fork which had this two args, but i cant find it anymore.

**Comment by Akianonymus** [comment]
> the main problem of looping over files in the main function is that if somebody uses `--start-at <TIME>` then the bot waits for that time when the first file is finished, but the solution I'm talking about is more straight and simpler.

I have pushed some fixes, to address that issue.

**Comment by Insomniac5** [comment]
> @Insomniac5, it will also create a log with the name same as the selected accounts file.

No, it created the log file with the name of the json I put in the arg

**Pull request closed without merging**
