### PR TITLE
addition of --send-to-webhook flag.

### PR DESCRIPTION
**Pull request by AG4lyf**
its one of the most important flag as for me. 
its useful when you are using a VPS. and don't want to go all the way to vps ssh and check if its working or not. hooking into program std. its a lot hectic
specially when you have it setup to run automatically on cron job.

### CODE REVIEW

**Comment by farshadz1997** [comment]
Your pr looks good but please update it with new changes then I'll merge it.

**Comment by AG4lyf** [comment]
Check now

**Comment by niklasbaranski** [comment]
please give option to add a other webhook for the logs, so that the result channel stays clean.

**Comment by AG4lyf** [comment]
It was talked about 
the answer was

since the report always comes when the bot have completed it process. 
the main thing is always in end. so there's no 'need' of cleaning. 
you can have a dedicated webhook for result then why can't you have dedicated channels.

**Pull request merged**
