### PR TITLE
Check if msn game is finished

### PR DESCRIPTION
**Pull request by tommaso-ascani**
Added a check at the bottom of the msn game to control if is finished by 'gamestate' value, repeating the function untill the game is done (for real).
I tested 2/3 days and it seems to work fine but i will improve it step by step (for example i think now --repeat-shopping is useless).

### CODE REVIEW

**Comment by Prabh-Saini** [comment]
I always wanted to do this, I was just to lazy haha. The code is looking super good! One small idea I have is changing the scroll method, instead we could run a javascript function which would move MSN shopping to the top of the screen and also only have one card (although the functions that calculate the correct card should remain, in case Microsoft does patch the current solution). FYI, the script is:

```js
var msnShoppingGamePane = document.querySelector("shopping-page-base")
    ?.shadowRoot.querySelector("shopping-homepage")
    ?.shadowRoot.querySelector("msft-feed-layout")
    ?.shadowRoot.querySelector("msn-shopping-game-pane");
 
if (msnShoppingGamePane != null) {
    msnShoppingGamePane.style.setProperty("grid-area", "slot1");
    msnShoppingGamePane.setAttribute('gamestate', 'active');
    msnShoppingGamePane.cardsPerGame = 1;
    msnShoppingGamePane.resetGame();
}
```
I think this will not only speed up the bot but also reduce data usage. Regardless I've noticed this isn't your first awesome pull request, so keep up the good work! 🚀

**Comment by tommaso-ascani** [comment]
@Prabh-Saini I merged your code with the main, then i tested and it seems to works fine, tomorrow i'll run the bot and i'll test the complete code.

Hope this pr will be merged quickly because i don't want to fill it with useless commit of me merging farshadz master branch  🤣

**Comment by farshadz1997** [comment]
Hi, 

Your changes look good, I'll test it tomorrow and if everything goes right then I'll merge it.

@Prabh-Saini this section of code

```msn.js

if (msnShoppingGamePane != null) {
    msnShoppingGamePane.style.setProperty("grid-area", "slot1");
    msnShoppingGamePane.setAttribute('gamestate', 'active');
    msnShoppingGamePane.cardsPerGame = 1;
    msnShoppingGamePane.resetGame();
}
```

I haven't tested this but it seems like it sets the game to active when it's not, when it has already been completed is it a good idea to reset the game and do it again? wouldn't this make a risk?

**Comment by tommaso-ascani** [comment]
@farshadz1997 Thanks, now i'm resolving some problems at the end of the game and i will check also your possible issue

**Comment by tommaso-ascani** [comment]
@Prabh-Saini There is a problem with you js script, i can't understand why it runs one time but if i refresh the page and do it again, don't work no more and bot remains stuck.
It seems that cannot execute the script more than one time, but if i try manually to run the script on chrome console works multiple times, i can't understand, some advice?

**Comment by tommaso-ascani** [comment]
@Prabh-Saini I couldn't get the code work with your js script, don't know why do not work more then 1 time in the same page, now the code seems to run correctly and in the coming days i will rewrite it trying to understand more the problem

**Comment by Prabh-Saini** [comment]
> Hi,
> 
> Your changes look good, I'll test it tomorrow and if everything goes right then I'll merge it.
> 
> @Prabh-Saini this section of code
> 
> ```js
> if (msnShoppingGamePane != null) {
>     msnShoppingGamePane.style.setProperty("grid-area", "slot1");
>     msnShoppingGamePane.setAttribute('gamestate', 'active');
>     msnShoppingGamePane.cardsPerGame = 1;
>     msnShoppingGamePane.resetGame();
> }
> ```
> 
> I haven't tested this but it seems like it sets the game to active when it's not, when it has already been completed is it a good idea to reset the game and do it again? wouldn't this make a risk?

Your right, we should not reset the game because then it will prompt the script to keep completing msn shopping even though it has actually already been completed.

**Comment by tommaso-ascani** [comment]
@Prabh-Saini In the actual solution there isn't your js script due to it stucks when be executed more then 1 time in the same frame, i don't know why.
In fact if you see the code i create a new browser tab to reload everything and check the game.
I will try if with this tab solution i can re-implement your script

**Comment by Prabh-Saini** [comment]
Hey @tommaso-ascani, that's okay whatever you think is good. I'll try the script out and let you know what happens.

**Comment by tommaso-ascani** [comment]
@Prabh-Saini Ok, i've tried it for 2 days and at the moment no problems showed up

**Comment by tommaso-ascani** [comment]
@Prabh-Saini Yes, if you test it and give me a feedback for me it's even better.
Actually i tested on PC (Windows 10 OS), RaspberryPi (DietPi OS) and VM with (Ubuntu OS)

**Comment by Prabh-Saini** [comment]
Hey there, I tried running your script and I got this issue:
```shell
Message: javascript error: Cannot read properties of null (reading 'shadowRoot')
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
        [a lot of words here]
```
I guess this is because the script is unable to find the game. This could probably be easily resolved simply by checking if msn shopping game exists by returning its value in javascript.

**Comment by tommaso-ascani** [comment]
@Prabh-Saini I'm rewriting the code including your js scrpt but sometimes the stucks with no reasong, i'm trying to understand but i think that the js script execution creates some problems

**Comment by farshadz1997** [comment]
@tommaso-ascani There's one possible thing that can cause an error, I need more time to test it. I'll make sure to let you know if any changes are needed.

**Comment by tommaso-ascani** [comment]
@farshadz1997 I think i will close this pr, rewrite and test the code untill is fine, then i reopem PR.
Like this it's not working fine but there are some things that don't work and i don't know the reason

**Pull request closed without merging**
