### PR TITLE
Add support for proxy authentication

### PR DESCRIPTION
**Pull request by Akianonymus**
.

### CODE REVIEW

**Comment by farshadz1997** [comment]
Hi, I have tested this with my own proxy that has auth but it still asks me for username and password.

**Comment by steathy** [comment]
> Hi, I have tested this with my own proxy that has auth but it still asks me for username and password.

I tested it's working fine for me. Are you sure you were using correct auth info?

**Comment by steathy** [comment]
> @Akianonymus @steathy I have tried it one more time, I removed `proxy-server` arg from selenium, `isProxyWorking` confirmed that my proxy was working and loaded the extension on the browser but when I checked my IP it returned my original IP, not the proxy. any idea?

I did some research. It might be the manifest version issue. The chrome extension code pushed by @Akianonymus uses manifest v2, which stops working in newer chromedriver versions. (https://developer.chrome.com/docs/extensions/migrating/mv2-sunset/) I am still using a modified old version that still supports v2.

There are two solutions:
1. upgrade to manifest v3. I am not an expert on chrome extensions but you can find some solutions on stackoverflow. For example: https://stackoverflow.com/a/75258425
2. use selenium-wire. (https://github.com/wkeeling/selenium-wire) It's a little overkill but very easy to implement. However, it do require openssl, which might have compatibility issues on different platforms. 

Also I suggest your program check proxy using AWS's url: http://checkip.amazonaws.com/. You can easily get the proxy ip address from the response in plain text.

Thanks for the great work!

**Review by farshadz1997 — COMMENTED** [review]
added stealth to launch browser & resolved conflicts

**Pull request merged**
