### PR TITLE
Added TOTP support using pyotp

### PR DESCRIPTION
**Pull request by lnx00**
This makes it possible to use the bot on 2FA protected accounts by (optionally) providing the TOTP secret in the _accounts.json_ file.
The bot will automatically generate a TOTP code if it detects the 2FA screen using [pyotp](https://github.com/pyauth/pyotp).

### CODE REVIEW

**Comment by farshadz1997** [comment]
That's nice but there's an issue with it. you used waitUntilVisibile to wait for the element in 2FA page, if someone has entered TOTP secret but disabled it for any reason and forgot to remove it from account then it bot returns TimeoutException which cause bot to go into a loop, I recommend checking for existence for element or check the URL to make sure does it ask for 2FA code or not.

**Comment by lnx00** [comment]
Sure, I'll fix that. I thought that Selenium would simply continue if the element hasn't been found after the timeout.

**Comment by lnx00** [comment]
It should now work as intended. I've also added a TOTP exception that gets raised if 2FA is enabled, but no secret was provided.

**Comment by farshadz1997** [comment]
What would happen if the entered code was invalid?

**Comment by lnx00** [comment]
A wrong TOTP code causes the bot to continuously try to log into bing. Do you prefer a check that makes sure the TOTP code was correct?

**Comment by farshadz1997** [comment]
Maybe raise an exception then skip the account if the code was invalid, what do you think?

**Comment by lnx00** [comment]
I can do that. How can the account be skipped though? Do you have ab existing logic for that? Don't exceptions cause the bot to restart the farming process?

**Comment by lnx00** [comment]
Alright, it should work as intended now. If the TOTP code was invalid, an _TOTPInvalidException_ will be raised and the current account is skipped. Also if a TOTP code is required, but no secret was provided, the bot will wait for 5 seconds so the user can manually input the code before the exception gets raised.

I've tested it and it seems to work fine in both scenarios.

**Comment by Prabh-Saini** [comment]
hey @farshadz1997 once you push this update could you also push your updates too because I want to add a few features on top

**Pull request merged**
